# Welcome to Jekyll!
#

# Site settings
title: Welcome
description: |
  Another fine responsive  
  site template freebie  
  crafted by [HTML5 UP](http://html5up.net)
owner: wuchengcheng # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: wucheng110120@sina.com
baseurl: "https://wuchengcheng110120.github.io" # the subpath of your site, e.g. /blog
url: "https://wuchengcheng110120.github.io" # the base hostname & protocol for your site
social:
  知乎: https://twitter.com/<username>
  github: https://github.com/wuchengcheng110120
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed

theme: jekyll-theme-cayman